name: Build and upload to PyPI

# Build on every workflow_dispatch, branch push, tag push, and pull request change
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: |
        python -m build
    - name: Publish distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write # Added permission for GitHub Actions to push tags